package com.bluepilot.userservice.constants

import com.bluepilot.entities.ESIAndPFDetails


object ESiAndPfFieldsMap{
    private val instance = ESIAndPFDetails::class.members
    val esiAndPfDetailsMap = listOf(
        instance.first { it.name == "empCode" },
        instance.first { it.name == "uanNo" },
        instance.first { it.name == "pfNoOrPfMemberId" },
        instance.first { it.name == "esicNo" },
        instance.first { it.name == "adhaarName" },
        instance.first { it.name == "gender" },
        instance.first { it.name == "maritalStatus" },
        instance.first { it.name == "empDob" },
        instance.first { it.name == "empDoj" },
        instance.first { it.name == "mobNo" },
        instance.first { it.name == "fatherOrHusbandName" },
        instance.first { it.name == "relWithEmp" },
        instance.first { it.name == "pf" },
        instance.first { it.name == "esi" },
        instance.first { it.name == "pt" },
        instance.first { it.name == "email" },
        instance.first { it.name == "nationality" },
        instance.first { it.name == "adhaarNo" },
        instance.first { it.name == "panNo" },
        instance.first { it.name == "bankAccountNo" },
        instance.first { it.name == "bankName" },
        instance.first { it.name == "ifscCode" },
        instance.first { it.name == "flatOrHouseNo" },
        instance.first { it.name == "streetNo" },
        instance.first { it.name == "landMark" },
        instance.first { it.name == "state" },
        instance.first { it.name == "dist" },
        instance.first { it.name == "flatOrHouseNo" },
        instance.first { it.name == "streetNo" },
        instance.first { it.name == "landMark" },
        instance.first { it.name == "state" },
        instance.first { it.name == "dist" },
        instance.first { it.name == "fatherName" },
        instance.first { it.name == "adhaarCardOfFather" },
        instance.first { it.name == "dobOfFather" },
        instance.first { it.name == "motherName" },
        instance.first { it.name == "adhaarCardOfMother" },
        instance.first { it.name == "dobOfMother" },
        instance.first { it.name == "wifeName" },
        instance.first { it.name == "adhaarCardOfWife" },
        instance.first { it.name == "dobOfWife" },
        instance.first { it.name == "childOne" },
        instance.first { it.name == "adhaarCardOfChildOne" },
        instance.first { it.name == "genderOfChildOne" },
        instance.first { it.name == "dobOfChildOne" },
        instance.first { it.name == "childTwo" },
        instance.first { it.name == "adhaarCardOfChildTwo" },
        instance.first { it.name == "genderOfChildTwo" },
        instance.first { it.name == "dobOfChildTwo" },
        instance.first { it.name == "childThree" },
        instance.first { it.name == "adhaarCardOfChildThree" },
        instance.first { it.name == "genderOfChildThree" },
        instance.first { it.name == "dobOfChildThree" },
        instance.first { it.name == "childFour" },
        instance.first { it.name == "adhaarCardOfChildFour" },
        instance.first { it.name == "genderOfChildFour" },
        instance.first { it.name == "dobOfChildFour" },
        instance.first { it.name == "childFive" },
        instance.first { it.name == "adhaarCardOfChildFive" },
        instance.first { it.name == "genderOfChildFive" },
        instance.first { it.name == "dobOfChildFive" },
        instance.first { it.name == "nominee" },
        instance.first { it.name == "salaryCategory" },
        instance.first { it.name == "grossSalaryOfFullMonth" },
        instance.first { it.name == "basic" },
        instance.first { it.name == "hra" },
        instance.first { it.name == "conveyAllow" },
        instance.first { it.name == "cityCompAllow" },
        instance.first { it.name == "medAllow" },
        instance.first { it.name == "eduAllow" },
        instance.first { it.name == "transport" },
        instance.first { it.name == "tea" },
        instance.first { it.name == "mobileAllow" },
        instance.first { it.name == "newsPaper" },
        instance.first { it.name == "hostelAllow" },
        instance.first { it.name == "washingAllow" },
        instance.first { it.name == "foodAllow" },
        instance.first { it.name == "total" },
        instance.first { it.name == "remark" }
    )
}