server:
  servlet:
    context-path: /user-service
  port: ${PORT:9003}

spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST:localhost}:${POSTGRESQL_PORT:5432}/blue_pilot
    username: ${POSTGRESQL_USER:root}
    password: ${POSTGRESQL_PASSWORD:pilot}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:5MB}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_URL:http://localhost:8761/eureka/}

config:
  esi:
    file-name: ${ESI_FILE_NAME:ESI_PF.xlsx}
    sheet-name: ${ESI_SHEET_NAME:NEW EMP DETAILS}
    hr-gmail: ${HR_GMAIL:bluepilot.vinno@gmail.com}

  cms:
    client-code: ${CMS_CLIENT_CODE:VINNOVATE}
    product-code: ${CMS_PRODUCT_CODE:SALPAY}
    payment-type: ${CMS_PAYMENT_TYPE:IFT}
    debit-account-number: ${CMS_DEBIT_ACCOUNT_NUMBER:2513088025}
    bank-code: ${CMS_BANK_CODE:M}
    debit-narration: ${CMS_DEBIT_NARRATION:Salary Debit}
    credit-narration: ${CMS_CREDIT_NARRATION:Salary Credit}

api-config:
  openApis:

aws:
  sqs:
    profile: ${SQS_PROFILE:default}
    region: ${SQS_REGION:us-east-1}
    endpoint: ${SQS_ENDPOINT:http://localstack:4566}
    queue-url: ${SQS_QUEUE_URL:http://localstack:4566/000000000000/notification-queue}
