package com.bluepilot.coreservice.models.responses

import java.math.BigDecimal

data class EmployeeSalaryContext(
    val totalWorkingDays: BigDecimal,
    val totalPayableDays: BigDecimal,
    val basic: BigDecimal,
    val hra: BigDecimal,
    val specialAllowances: BigDecimal,
    val performanceIncentive: BigDecimal,
    var oneTimeIncentive: BigDecimal,
    val pt: BigDecimal,
    val it: BigDecimal,
    val pf: BigDecimal,
    val esi: BigDecimal,
    val advance: BigDecimal,
    val grossEarning: BigDecimal,
    val grossDeductions: BigDecimal,
    val grossPay: BigDecimal,
    val ytdBasic: BigDecimal,
    val ytdHra: BigDecimal,
    val ytdSpecialAllowances: BigDecimal,
    val ytdBonus: BigDecimal,
    val ytdEarnings: BigDecimal,
    val ytdPt: BigDecimal,
    val ytdPf: BigDecimal,
    val ytdEsi: BigDecimal,
    val ytdIt: BigDecimal,
    val ytdOtherDeductions: BigDecimal,
    val ytdDeductions: BigDecimal,
    val ytdPmEarnings: BigDecimal,
    val ytdPmBasic: BigDecimal,
    val ytdPmHra: BigDecimal,
    val ytdPmSpecialAllowances: BigDecimal,
    val ytdPmBonus: BigDecimal,
    val ytdPmDeductions: BigDecimal,
    val ytdPmPt: BigDecimal,
    val ytdPmPf: BigDecimal,
    val ytdPmEsi: BigDecimal,
    val ytdPmIt: BigDecimal,
    val ytdPmOtherDeductions: BigDecimal,
)
