package com.bluepilot.userservice.generators

import com.bluepilot.enums.Gender
import com.bluepilot.enums.MaritalStatus
import com.bluepilot.enums.Nominee
import com.bluepilot.enums.RelationWithEmp
import com.bluepilot.enums.Required
import com.bluepilot.enums.SalaryCategory
import com.bluepilot.userservice.models.requests.UpdateESIAndPFDetailsByHRRequest
import com.bluepilot.userservice.models.requests.UpdateESIAndPFDetailsByUserRequest
import java.math.BigDecimal
import java.sql.Date

object UpdateESIAndPFDetailsRequestGenerator {
    fun getESIAndPFDetailsByUserRequest(
        userId: Long = 0,
        adhaarName: String = "testaadhaaar",
        gender: Gender = Gender.MALE,
        maritalStatus: MaritalStatus = MaritalStatus.UNMARRIED,
        empDob: Date = Date.valueOf("2000-05-01"),
        mobNo: Long = 123456789L,
        fatherOrHusbandName: String = "father",
        relWithEmp: RelationWithEmp = RelationWithEmp.FATHER,
        adhaarNo: String = "aadhaar",
        panNo: String = "panNo",
        flatOrHouseNo: String = "flatNo",
        streetNo: String = "street",
        landMark: String = "landmark",
        state: String = "state",
        dist: String = "district",
        fatherName: String = "father",
        adhaarCardOfFather: String = "aadhaar",
        dobOfFather: Date = Date.valueOf("2000-05-01"),
        motherName: String = "mother",
        adhaarCardOfMother: String = "aadhaar",
        dobOfMother: Date = Date.valueOf("2000-05-01"),
        wifeName: String = "wife",
        adhaarCardOfWife: String = "aadhaar",
        dobOfWife: Date = Date.valueOf("2000-05-01"),
        childOne: String = "childOne",
        adhaarCardOfChildOne: String = "aadhaar",
        genderOfChildOne: Gender = Gender.values().random(),
        dobOfChildOne: Date = Date.valueOf("2000-05-01"),
        childTwo: String = "childTwo",
        adhaarCardOfChildTwo: String = "aadhaar",
        genderOfChildTwo: Gender = Gender.values().random(),
        dobOfChildTwo: Date = Date.valueOf("2000-05-01"),
        childThree: String = "childThree",
        adhaarCardOfChildThree: String = "aadhaar",
        genderOfChildThree: Gender = Gender.values().random(),
        dobOfChildThree: Date = Date.valueOf("2000-05-01"),
        childFour: String = "childFour",
        adhaarCardOfChildFour: String = "aadhaar",
        genderOfChildFour: Gender = Gender.values().random(),
        dobOfChildFour: Date = Date.valueOf("2000-05-01"),
        childFive: String = "childFive",
        adhaarCardOfChildFive: String = "aadhaar",
        genderOfChildFive: Gender = Gender.values().random(),
        dobOfChildFive: Date = Date.valueOf("2000-05-01"),
        nominee: Nominee = Nominee.values().random(),
    ): UpdateESIAndPFDetailsByUserRequest {
        return UpdateESIAndPFDetailsByUserRequest(
            userId = userId,
            adhaarName = adhaarName,
            gender = gender,
            maritalStatus = maritalStatus,
            empDob = empDob,
            mobNo = mobNo,
            fatherOrHusbandName = fatherOrHusbandName,
            relWithEmp = relWithEmp,
            adhaarNo = adhaarNo,
            panNo = panNo,
            flatOrHouseNo = flatOrHouseNo,
            streetNo = streetNo,
            landMark = landMark,
            state = state,
            dist = dist,
            fatherName = fatherName,
            adhaarCardOfFather = adhaarCardOfFather,
            dobOfFather = dobOfFather,
            motherName = motherName,
            adhaarCardOfMother = adhaarCardOfMother,
            dobOfMother = dobOfMother,
            wifeName = wifeName,
            adhaarCardOfWife = adhaarCardOfWife,
            dobOfWife = dobOfWife,
            childOne = childOne,
            adhaarCardOfChildOne = adhaarCardOfChildOne,
            genderOfChildOne = genderOfChildOne,
            dobOfChildOne = dobOfChildOne,
            childTwo = childTwo,
            adhaarCardOfChildTwo = adhaarCardOfChildTwo,
            genderOfChildTwo = genderOfChildTwo,
            dobOfChildTwo = dobOfChildTwo,
            childThree = childThree,
            adhaarCardOfChildThree = adhaarCardOfChildThree,
            genderOfChildThree = genderOfChildThree,
            dobOfChildThree = dobOfChildThree,
            childFour = childFour,
            adhaarCardOfChildFour = adhaarCardOfChildFour,
            genderOfChildFour = genderOfChildFour,
            dobOfChildFour = dobOfChildFour,
            childFive = childFive,
            adhaarCardOfChildFive = adhaarCardOfChildFive,
            genderOfChildFive = genderOfChildFive,
            dobOfChildFive = dobOfChildFive,
            nominee = nominee
        )
    }

    fun getESIAndPFDetailsByHRRequest(
        userId: Long = 0,
        empCode: String = "emp",
        uanNo: String = "uan",
        pfNoOrPfMemberId: String = "Test",
        esicNo: String = "esic",
        empDoj: Date = Date.valueOf("2000-05-01"),
        pf: Required = Required.YES,
        esi: Required = Required.YES,
        pt: Required = Required.YES,
        email: String = "email",
        nationality: String = "nationality",
        bankAccountNo: String = "bankNo",
        bankName: String = "bankname",
        ifscCode: String = "ifsc",
        salaryCategory: SalaryCategory = SalaryCategory.MONTHLY,
        grossSalaryOfFullMonth: BigDecimal = BigDecimal(100.00),
        basic: BigDecimal = BigDecimal(100.00),
        hra: BigDecimal = BigDecimal(100.00),
        conveyAllow: BigDecimal = BigDecimal(100.00),
        cityCompAllow: BigDecimal = BigDecimal(100.00),
        medAllow: BigDecimal = BigDecimal(100.00),
        eduAllow: BigDecimal = BigDecimal(100.00),
        transport: BigDecimal = BigDecimal(100.00),
        tea: BigDecimal = BigDecimal(100.00),
        mobileAllow: BigDecimal = BigDecimal(100.00),
        newsPaper: BigDecimal = BigDecimal(100.00),
        hostelAllow: BigDecimal = BigDecimal(100.00),
        washingAllow: BigDecimal = BigDecimal(100.00),
        foodAllow: BigDecimal = BigDecimal(100.00),
        total: BigDecimal = BigDecimal(1000.00),
        remark: String = "remark"
    ): UpdateESIAndPFDetailsByHRRequest {
        return UpdateESIAndPFDetailsByHRRequest(
            userId = userId,
            empCode = empCode,
            uanNo = uanNo,
            pfNoOrPfMemberId = pfNoOrPfMemberId,
            esicNo = esicNo,
            empDoj = empDoj,
            pf = pf,
            esi = esi,
            pt = pt,
            email = email,
            nationality = nationality,
            bankAccountNo = bankAccountNo,
            bankName = bankName,
            ifscCode = ifscCode,
            salaryCategory = salaryCategory,
            grossSalaryOfFullMonth = grossSalaryOfFullMonth,
            basic = basic,
            hra = hra,
            conveyAllow = conveyAllow,
            cityCompAllow = cityCompAllow,
            medAllow = medAllow,
            eduAllow = eduAllow,
            transport = transport,
            tea = tea,
            mobileAllow = mobileAllow,
            newsPaper = newsPaper,
            hostelAllow = hostelAllow,
            washingAllow = washingAllow,
            foodAllow = foodAllow,
            total = total,
            remark = remark
        )
    }
}