package com.bluepilot.userservice.mappers

import com.bluepilot.entities.ESIAndPFDetails
import com.bluepilot.userservice.models.responses.UserESIAndPFDetailsResponse
import org.springframework.stereotype.Component

@Component
class ESIAndPFResponseMapper {
    fun mapESIAndPFResponse(esiAndPFDetails: ESIAndPFDetails): UserESIAndPFDetailsResponse {
        return UserESIAndPFDetailsResponse(
                id = esiAndPFDetails.id,
                empCode = esiAndPFDetails.empCode,
                uanNo = esiAndPFDetails.uanNo,
                pfNoOrPfMemberId = esiAndPFDetails.pfNoOrPfMemberId,
                esicNo = esiAndPFDetails.esicNo,
                adhaarName = esiAndPFDetails.adhaarName,
                gender = esiAndPFDetails.gender,
                maritalStatus = esiAndPFDetails.maritalStatus,
                empDob = esiAndPFDetails.empDob,
                empDoj = esiAndPFDetails.empDoj,
                mobNo = esiAndPFDetails.mobNo,
                fatherOrHusbandName = esiAndPFDetails.fatherName,
                relWithEmp = esiAndPFDetails.relWithEmp,
                pf = esiAndPFDetails.pf,
                esi = esiAndPFDetails.esi,
                pt = esiAndPFDetails.pt,
                email = esiAndPFDetails.email,
                nationality = esiAndPFDetails.nationality,
                adhaarNo = esiAndPFDetails.adhaarNo,
                panNo = esiAndPFDetails.panNo,
                bankAccountNo = esiAndPFDetails.bankAccountNo,
                bankName = esiAndPFDetails.bankName,
                ifscCode = esiAndPFDetails.ifscCode,
                flatOrHouseNo = esiAndPFDetails.flatOrHouseNo,
                streetNo = esiAndPFDetails.streetNo,
                landMark = esiAndPFDetails.landMark,
                state = esiAndPFDetails.state,
                dist = esiAndPFDetails.dist,
                fatherName = esiAndPFDetails.fatherName,
                adhaarCardOfFather = esiAndPFDetails.adhaarCardOfFather,
                dobOfFather = esiAndPFDetails.dobOfFather,
                motherName = esiAndPFDetails.motherName,
                adhaarCardOfMother = esiAndPFDetails.adhaarCardOfMother,
                dobOfMother = esiAndPFDetails.dobOfMother,
                wifeName = esiAndPFDetails.wifeName,
                adhaarCardOfWife = esiAndPFDetails.adhaarCardOfWife,
                dobOfWife = esiAndPFDetails.dobOfWife,
                childOne = esiAndPFDetails.childOne,
                adhaarCardOfChildOne = esiAndPFDetails.adhaarCardOfChildOne,
                genderOfChildOne = esiAndPFDetails.genderOfChildOne,
                dobOfChildOne = esiAndPFDetails.dobOfChildOne,
                childTwo = esiAndPFDetails.childTwo,
                adhaarCardOfChildTwo = esiAndPFDetails.adhaarCardOfChildTwo,
                genderOfChildTwo = esiAndPFDetails.genderOfChildTwo,
                dobOfChildTwo = esiAndPFDetails.dobOfChildTwo,
                childThree = esiAndPFDetails.childThree,
                adhaarCardOfChildThree = esiAndPFDetails.adhaarCardOfChildThree,
                genderOfChildThree = esiAndPFDetails.genderOfChildThree,
                dobOfChildThree = esiAndPFDetails.dobOfChildThree,
                childFour = esiAndPFDetails.childFour,
                adhaarCardOfChildFour = esiAndPFDetails.adhaarCardOfChildFour,
                genderOfChildFour = esiAndPFDetails.genderOfChildFour,
                dobOfChildFour = esiAndPFDetails.dobOfChildFour,
                childFive = esiAndPFDetails.childFive,
                adhaarCardOfChildFive = esiAndPFDetails.adhaarCardOfChildFive,
                genderOfChildFive = esiAndPFDetails.genderOfChildFive,
                dobOfChildFive = esiAndPFDetails.dobOfChildFive,
                nominee = esiAndPFDetails.nominee,
                salaryCategory = esiAndPFDetails.salaryCategory,
                grossSalaryOfFullMonth = esiAndPFDetails.grossSalaryOfFullMonth,
                basic = esiAndPFDetails.basic,
                hra = esiAndPFDetails.hra,
                conveyAllow = esiAndPFDetails.conveyAllow,
                cityCompAllow = esiAndPFDetails.cityCompAllow,
                medAllow = esiAndPFDetails.medAllow,
                eduAllow = esiAndPFDetails.eduAllow,
                transport = esiAndPFDetails.transport,
                tea = esiAndPFDetails.tea,
                mobileAllow = esiAndPFDetails.mobileAllow,
                newsPaper = esiAndPFDetails.newsPaper,
                hostelAllow = esiAndPFDetails.hostelAllow,
                washingAllow = esiAndPFDetails.washingAllow,
                foodAllow = esiAndPFDetails.foodAllow,
                total = esiAndPFDetails.total,
                remark = esiAndPFDetails.remark
            )
    }
}